spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mysql://127.0.0.1/demo?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null  #返回结果带是null不返回
server:
  servlet:
    context-path: /sell
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml

wechat:
  mpAppId:  123456
  mpAppSecret:  1212331
  mchId: 111
  mchKey: 111
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: https://www/baidu.com

